language: go

go:
  - 1.6

before_install:
  - go get github.com/rancher/trash

install:
  - trash
  - go get -t -v ./...

script:
  - go build -o open-falcon
  - go build ./modules/agent
  - go build ./modules/aggregator
  - go build ./modules/alarm
  - go build ./modules/api
  - go build ./modules/gateway
  - go build ./modules/graph
  - go build ./modules/hbs
  - go build ./modules/judge
  - go build ./modules/nodata
  - go build ./modules/sender
  - go build ./modules/task
  - go build ./modules/transfer

after_success:
  - go test -race -coverprofile=coverage.txt -covermode=atomic github.com/open-falcon/falcon-plus/modules/api/test
  - bash <(curl -s https://codecov.io/bash)
